### ISSUE TITLE
Name of automatic module 'jblas' is unstable, it is derived from the module's file name.

### ISSUE THREAD

**Issue by KNejad** [jblas-project/jblas#112]
I am getting this warning in Eclipse when trying to require jblas in a module-info.java file. Would it be possible to add support for Java 11 modules and do any required renames to the project structure to accommodate this?

**Comment by mikiobraun** [comment]
Can you give a bit more background what would be needed? I'm kinda wary to break backwards compatibility..

**Comment by KNejad** [comment]
HI @mikiobraun I am fairly new to Java (only a couple of months of experience), so I am not so sure but from what I have read all that is needed is to add a module-info.java file at the root of your project like below. However you may be right that this could break some backwards compatibility. I wish I could help more but truthfully I am just not that experienced with Java.

```
module org.jblas {
}
```

**Comment by mikiobraun** [comment]
I did a release right now, but for other reasons I'm still building it as Java 8 (javah is missing later and I haven't figured out how to do that yet).

Closing the issue for now, feel free to repon.
