### ISSUE TITLE
 LAPACK 3.3.0 Bug: "XERBLA: Error on argument -1 for *unknown function* DLASD8 (how odd!)"

### ISSUE THREAD

**Issue by adamci** [jblas-project/jblas#116]
I hit this recently using jblas version 1.2.4:
```
java.lang.IllegalArgumentException: XERBLA: Error on argument -1 for *unknown function* DLASD8 (how odd!)
```
This was caused by [a change introduced in LAPACK 3.3.0](https://github.com/Reference-LAPACK/lapack-release/blob/lapack-3.3.0/SRC/dlasd6.f#L288), where a convergence failure in DLASD6's call of DLASD8 is subsequently reported to XERBLA, instead of allowing the error call to percolate up. This kind of issue has been [documented in the past](http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=13&t=4586).
Could we upgrade the LAPACK depenency for jblas to at least version 3.6.0, [where this bug was fixed](https://github.com/Reference-LAPACK/lapack-release/blob/lapack-3.8.0/SRC/dlasd6.f#L419)? If that change is too involved, a faster fix would be to add some special case handling in our XERBLA monkey patch to ignore calls with arguments of DLASD8 and -1, as that can't happen anywhere else in the code for LAPACK 3.4.2.

**Comment by mikiobraun** [comment]
Thanks for pointing this out. Switching LAPACK versions is a bit difficult because I also use the source files to collect the function name signatures and the format changed at some point. I always wanted to revert this situation, but haven't gotten around to it yet.

I have, however, just released jblas 1.2.5 which now uses openblas (at least on amd64 for now). Let me know if the problem persists there.

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by adamci** [comment]
Thank you for the response and the new version of jblas!
What version of OpenBLAS are you using?

**Comment by mikiobraun** [comment]
(Sorry for deleting your comments, but there were 14 identical ones)

The one that came with Ubuntu 18.04, which appears to be 0.2.20+ds-4.

**Comment by adamci** [comment]
I think we're good to close this, as I've been running on 1.2.5 without issues thus far
