### ISSUE TITLE
I did some benchmark somehow the matrix mul performs consistently slower than java ojalgo.

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [jblas-project/jblas#125]
it also gives out some sort of log that cleans while doing work.

result>
start test
552035845299
testfinished,with Primitive32Matrix .ojalgo(no try catch)
start test
-- org.jblas INFO Starting temp DLL cleanup task.
-- org.jblas INFO Deleted 4 unused temp DLL libraries from C:\Users\sumur\AppData\Local\Temp
600934105500
testfinished,with matrix .jblas(no try catch)

jblas>
public void plugstart(){
		System.out.println("start test");
		long st=System.nanoTime();
		org.jblas.FloatMatrix a=org.jblas.FloatMatrix.rand(10000,10000);
		org.jblas.FloatMatrix b=org.jblas.FloatMatrix.rand(10000,10000);
		b=a.mmul(b);
		System.out.println(System.nanoTime()-st);
		System.out.println("testfinished,with matrix .jblas(no try catch)");
	}

ojalgo>
public void plugstart(){
		System.out.println("start test");
		long st=System.nanoTime();
		org.jblas.FloatMatrix a=org.jblas.FloatMatrix.rand(10000,10000);
		org.jblas.FloatMatrix b=org.jblas.FloatMatrix.rand(10000,10000);
		b=a.mmul(b);
		System.out.println(System.nanoTime()-st);
		System.out.println("testfinished,with matrix .jblas(no try catch)");
	}

Well if you are curious about id add is similar then

start test
600980501
testfinished,with Primitive32Matrix .ojalgo(no try catch)
start test
332480200
testfinished,with matrix .jblas(no try catch)

Yup as you can see only the mul,has some problem.any idea?I believe using benchmark tools does not matter as i scaled it very high.
So as you can see the gap is magnified,like in a very huge number,not in terms of seconds.
Also I disabled any windows update and any extra services through registry explicitly.The cpu is constantly hogged by the testing application only.
The setup is kept to be very constant,and minimal.No random notifications or another application pop up without my permission.
I also did not use the computer in any way.Just enter and leave.
Lastly,did I repeat the test,yes.all similarly slower within 10 percent range.

**Comment by mikiobraun** [comment]
Hi,

which operating system was this on?

**Comment by xwaeaewcrhomesysplug** [comment]
windows_intel64bit
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.19041 N/A Build 19041

**Comment by mikiobraun** [comment]
Ah, I see. Yeah, I Windows binaries are unfortunately linked against non-optimized LAPACK and BLAS libraries. 

This is mentioned (a bit cryptically) here: https://github.com/jblas-project/jblas/wiki/Supported-Platforms

The problem is that ATLAS (the native BLAS library) has a very complex build process that I could never get to run on Windows. However, I recently started using OpenBLAS, once I find time to run that, performance on Windows should improve a lot. Sorry about that.

**Comment by xwaeaewcrhomesysplug** [comment]
okok,it is fine.I could also become a tester for your binaries in the future too.^^

**Comment by xwaeaewcrhomesysplug** [comment]
BTW,don't worry about it too much since generally it is just around 10 percent slower than pure java ojalgo.

Like>
552035845299
testfinished,with Primitive32Matrix .ojalgo(no try catch)
start test
-- org.jblas INFO Starting temp DLL cleanup task.
-- org.jblas INFO Deleted 4 unused temp DLL libraries from C:\Users\sumur\AppData\Local\Temp
600934105500

or>
start test
-- org.jblas INFO Starting temp DLL cleanup task.
600251319500
testfinished,with matrix .jblas(no try catch)
start test
537240456800
testfinished,with Primitive32Matrix .ojalgo(no try catch)

both of these does not seem too bad,compare to jblas vs apache common.. or naive java2d array..

**Comment by xwaeaewcrhomesysplug** [comment]
One of the possibilities is that it take quite some time to also clean temp dll
Maybe we can manually trigger it before the calc.As like a setup process.
Which is honestly quite acceptable when given some documentation and guide.
Compare to boilerplate code for some frameworks...

**Comment by mikiobraun** [comment]
Yeah, the non-ATLAS code for the low level matrix operations is just very slow, not really optimized in terms of assembly instructions or memory access pattern.

Thanks for the offer for testing, I'll reply to this thread when there is some progress made.
