### ISSUE TITLE
org.jblas.FloatMatrix.loadCSVFile() prints to System.out

### ISSUE THREAD

**Issue by shanishalgi** [jblas-project/jblas#74]
Hello,

The loadCSVFile() method in the FloatMatrix class contains the following line:

``` java
System.out.println("Done reading file");
```

(Line 2085 in org.jblas.FloatMatrix.java in the jblas-1.2.3.jar available via Maven.)

imho - making applications which use JBlas print messages they did not intend to seems like a bad idea.  It would be nicer if this was either
a. removed, or
b. made optional via some verbosity flag.

**Comment by mikiobraun** [comment]
Hey, shanishalgi thanks for the very late reply.

I totally agree, thanks for the hint!

**Comment by mikiobraun** [comment]
fixed it.
