### ISSUE TITLE
Support for new libgfortran

### ISSUE THREAD

**Issue by axeldavy** [jblas-project/jblas#87]
Hi.

I use Archlinux, and now it seems libgfortran.so.3 is not available anymore (it's libgfortran.so.4 instead).
The configure and build of jblas works fine, but then when using jblas it won't work because it complains of missing libgfortran3.
symlink of libgfortran.so.3 to the libgfortran.so.4 caused "/usr/lib/libgfortran.so.3: version `GFORTRAN_1.0' not found"

**Comment by mikiobraun** [comment]
Hey axeldavy,

have you tried going into the configure.out and replacing the library there. Still the GFORTRAN_1.0 bug?

**Comment by axeldavy** [comment]
With the configure options "--libs=openblas --download-lapack --build-type=openblas"
I get the following configure.out

`BUILD_TYPE=openblas
CC=gcc
CCC=c99
CFLAGS=-fPIC -DHAS_CPUID
F77=gfortran
FOUND_JAVA=true
FOUND_NM=true
INCDIRS=-Iinclude -I/usr/lib/jvm/java-8-openjdk//include -I/usr/lib/jvm/java-8-openjdk//include/linux
JAVA_HOME=/usr/lib/jvm/java-8-openjdk/
LAPACK_HOME=./lapack-lite-3.1.1
LD=gcc
LDFLAGS=-shared -L/usr/lib
LIB=lib
LINKAGE_TYPE=dynamic
LOADLIBES=-lopenblas
MAKE=make
NM=nm
OS_ARCH=amd64
OS_ARCH_WITH_FLAVOR=amd64/sse3
OS_NAME=Linux
RUBY=ruby
SO=so`

There doesn't seem to be a way to specify the version of libgfortran.

**Comment by ejberry** [comment]
Is there any headway on this issue?

**Comment by mikiobraun** [comment]
Hey, sorry for the very late reply. I just released 1.2.5 which bumps dependencies to libgfortran.so.4, but more importantly now also has that in the jar and copies it from there if it cannot find it. Let me know if that works for you.

I'm closing the issue now because it is so old, feel free to reopen if it still matters.
