### ISSUE TITLE
JBLAS running very slow

### ISSUE THREAD

**Issue by Jesusdiazrivero** [jblas-project/jblas#93]
Hello,

I'm using JBLAS to solve a system of linear equations A*x = B such that A is a lower triangular matrix whose size can be up to 1000x1000.

DoubleMatrix x = Solve.solve(A, B);

And then I need to find the frobenius norm of the result,

double norm = x.norm2();

Changing only this, the performance using EJML (pure Java) is 3-4 times better. The methods used from this library are pretty much the same.

I'm wondering if I'm doing something wrong because this doesn't sound right. I downloaded the jar and included it in my project as instructed in the Getting Started section. This may be a silly question, but is there something else to download? Some DLLs?

Thank you

**Comment by mikiobraun** [comment]
Hi Jesus,

are you using Windows with 64bit? Unfortunately, building ATLAS for 64bit was difficult for a long time, so the supplied libraries are (pretty unoptimized) Fortran libraries. I've heard that 64bit compile works now, but never found the time to dig into it. Sorry.

More info: https://github.com/mikiobraun/jblas/wiki/Why-There-Is-No-64bit-Support-for-Windows

Best, -M
